CREATE SCHEMA IF NOT EXISTS TIKTAKTUK;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS TIKTAKTUK.USER_ACCOUNT (
  user_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.ROLE (
  role_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  role_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.ACCOUNT_ROLE (
  role_id UUID NOT NULL,
  user_id UUID NOT NULL,
  CONSTRAINT pk_account_role PRIMARY KEY (role_id, user_id),
  CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES TIKTAKTUK.ROLE(role_id) ON DELETE CASCADE,
  CONSTRAINT fk_user_account FOREIGN KEY (user_id) REFERENCES TIKTAKTUK.USER_ACCOUNT(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.CUSTOMER (
  customer_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  phone_number VARCHAR(20),
  full_name VARCHAR(100) NOT NULL,
  user_id UUID UNIQUE NOT NULL,
  CONSTRAINT fk_customer_user_account FOREIGN KEY (user_id) REFERENCES TIKTAKTUK.USER_ACCOUNT(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.ORGANIZER (
  organizer_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  organizer_name VARCHAR(100) NOT NULL,
  contact_email VARCHAR(100),
  user_id UUID UNIQUE NOT NULL,
  CONSTRAINT fk_organizer_user_account FOREIGN KEY (user_id) REFERENCES TIKTAKTUK.USER_ACCOUNT(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.VENUE (
  venue_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  venue_name VARCHAR(100) NOT NULL,
  capacity INTEGER NOT NULL CHECK (capacity > 0),
  address TEXT NOT NULL,
  city VARCHAR(100) NOT NULL,
  jenis_seating VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.EVENT (
  event_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  event_datetime TIMESTAMP NOT NULL,
  event_title VARCHAR(200) NOT NULL,
  venue_id UUID NOT NULL,
  organizer_id UUID NOT NULL,
  CONSTRAINT fk_event_venue FOREIGN KEY (venue_id) REFERENCES TIKTAKTUK.VENUE(venue_id) ON DELETE CASCADE,
  CONSTRAINT fk_event_organizer FOREIGN KEY (organizer_id) REFERENCES TIKTAKTUK.ORGANIZER(organizer_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.PROMOTION (
  promotion_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  promo_code VARCHAR(50) UNIQUE NOT NULL,
  discount_type VARCHAR(20) NOT NULL,
  discount_value NUMERIC(12,2) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  usage_limit INTEGER NOT NULL
);
