CREATE SCHEMA IF NOT EXISTS TIKTAKTUK;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS TIKTAKTUK.USER_ACCOUNT (
  user_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.ROLE (
  role_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  role_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.ACCOUNT_ROLE (
  role_id UUID NOT NULL,
  user_id UUID NOT NULL,
  CONSTRAINT pk_account_role PRIMARY KEY (role_id, user_id),
  CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES TIKTAKTUK.ROLE(role_id) ON DELETE CASCADE,
  CONSTRAINT fk_user_account FOREIGN KEY (user_id) REFERENCES TIKTAKTUK.USER_ACCOUNT(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.CUSTOMER (
  customer_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  phone_number VARCHAR(20),
  full_name VARCHAR(100) NOT NULL,
  user_id UUID UNIQUE NOT NULL,
  CONSTRAINT fk_customer_user_account FOREIGN KEY (user_id) REFERENCES TIKTAKTUK.USER_ACCOUNT(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.ORGANIZER (
  organizer_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  organizer_name VARCHAR(100) NOT NULL,
  contact_email VARCHAR(100),
  user_id UUID UNIQUE NOT NULL,
  CONSTRAINT fk_organizer_user_account FOREIGN KEY (user_id) REFERENCES TIKTAKTUK.USER_ACCOUNT(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.VENUE (
  venue_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  venue_name VARCHAR(100) NOT NULL,
  capacity INTEGER NOT NULL CHECK (capacity > 0),
  address TEXT NOT NULL,
  city VARCHAR(100) NOT NULL,
  jenis_seating VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.EVENT (
  event_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  event_datetime TIMESTAMP NOT NULL,
  event_title VARCHAR(200) NOT NULL,
  venue_id UUID NOT NULL,
  organizer_id UUID NOT NULL,
  CONSTRAINT fk_event_venue FOREIGN KEY (venue_id) REFERENCES TIKTAKTUK.VENUE(venue_id) ON DELETE CASCADE,
  CONSTRAINT fk_event_organizer FOREIGN KEY (organizer_id) REFERENCES TIKTAKTUK.ORGANIZER(organizer_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.SEAT (
  seat_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  seat_number VARCHAR(20) NOT NULL,
  zone VARCHAR(50),
  venue_id UUID NOT NULL,
  CONSTRAINT fk_seat_venue FOREIGN KEY (venue_id) REFERENCES TIKTAKTUK.VENUE(venue_id) ON DELETE CASCADE,
  CONSTRAINT uq_seat_number_venue UNIQUE (seat_number, venue_id)
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.ARTIST (
  artist_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(100) NOT NULL,
  genre VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.EVENT_ARTIST (
  event_id UUID NOT NULL,
  artist_id UUID NOT NULL,
  role VARCHAR(100),
  CONSTRAINT pk_event_artist PRIMARY KEY (event_id, artist_id),
  CONSTRAINT fk_event_artist_event FOREIGN KEY (event_id) REFERENCES TIKTAKTUK.EVENT(event_id) ON DELETE CASCADE,
  CONSTRAINT fk_event_artist_artist FOREIGN KEY (artist_id) REFERENCES TIKTAKTUK.ARTIST(artist_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK."ORDER" (
  order_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  payment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  customer_id UUID NOT NULL,
  event_id UUID NOT NULL,
  CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES TIKTAKTUK.CUSTOMER(customer_id) ON DELETE CASCADE,
  CONSTRAINT fk_order_event FOREIGN KEY (event_id) REFERENCES TIKTAKTUK.EVENT(event_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.TICKET_CATEGORY (
  category_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  category_name VARCHAR(100) NOT NULL,
  quota INTEGER NOT NULL CHECK (quota >= 0),
  price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
  tevent_id UUID NOT NULL,
  CONSTRAINT fk_ticket_category_event FOREIGN KEY (tevent_id) REFERENCES TIKTAKTUK.EVENT(event_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.TICKET (
  ticket_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  ticket_code VARCHAR(100) UNIQUE NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  order_id UUID NOT NULL,
  category_id UUID NOT NULL,
  CONSTRAINT fk_ticket_order FOREIGN KEY (order_id) REFERENCES TIKTAKTUK."ORDER"(order_id) ON DELETE CASCADE,
  CONSTRAINT fk_ticket_category FOREIGN KEY (category_id) REFERENCES TIKTAKTUK.TICKET_CATEGORY(category_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.HAS_RELATIONSHIP (
  customer_id UUID NOT NULL,
  ticket_id UUID NOT NULL,
  CONSTRAINT pk_has_relationship PRIMARY KEY (customer_id, ticket_id),
  CONSTRAINT fk_has_relationship_customer FOREIGN KEY (customer_id) REFERENCES TIKTAKTUK.CUSTOMER(customer_id) ON DELETE CASCADE,
  CONSTRAINT fk_has_relationship_ticket FOREIGN KEY (ticket_id) REFERENCES TIKTAKTUK.TICKET(ticket_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.PROMOTION (
  promotion_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  promo_code VARCHAR(50) UNIQUE NOT NULL,
  discount_type VARCHAR(20) NOT NULL,
  discount_value NUMERIC(12,2) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  usage_limit INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS TIKTAKTUK.ORDER_PROMOTION (
  promotion_id UUID NOT NULL,
  order_id UUID NOT NULL,
  CONSTRAINT pk_order_promotion PRIMARY KEY (promotion_id, order_id),
  CONSTRAINT fk_order_promotion_promotion FOREIGN KEY (promotion_id) REFERENCES TIKTAKTUK.PROMOTION(promotion_id) ON DELETE CASCADE,
  CONSTRAINT fk_order_promotion_order FOREIGN KEY (order_id) REFERENCES TIKTAKTUK."ORDER"(order_id) ON DELETE CASCADE
);
